### PR TITLE
Implement new config options for the Calendar module

### PR DESCRIPTION
**Pull request by dannya**
Implement many new useful config options for the Calendar module, and streamline some of the existing code.

The new options are off by default, so they should not affect existing installations of this component.

I've made a best-effort attempt to match the existing code style.

### CODE REVIEW

**Comment by accdc** [comment]
That's awesome, thank you! Since the calendar module is plug-n play within all of the TSG projects powered by jQuery, Dojo, and MooTools, are there any API specific commands present within the changes that would only apply to one, or do all of them follow the $A.method normalization process as present within the other module code?

I'll download a copy later this week and run tests across all of them to ensure that the changes port equally across all of them, which is what I do for all code changes that include the core module files. My apologies that this is a bit of a lengthy process, the purpose is to ensure interoperability.

All the best,
Bryan

**Comment by dannya** [comment]
Hi @accdc,
Most of my changes are internal to the existing functions (with a few refactorings of code into new internal functions), and of course new config options. These changes are mostly around data manipulation and a few modifications to the HTML construction, I've always used the existing $A.* methods rather than directly using jQuery methods.

I actually implemented most of this against R1.22 and forward-ported before the pull request. I even had my own version of "condenseYear" but refactored it to be closer to yours.

I've tested the changes by modifying the referenced script in bootstrap.htm, but please let me know if there are any regressions (especially in edge-cases), or if there are other code guidelines that are relevant.

I had a question actually, I noticed between R1.22 and R1.26 that 
`$A.internal.extend(true, dc.fn.current, dc.range.current);`
appears a lot at the top of the date modification functions, but it didn't seem to be doing much useful work, is this part of an ongoing refactoring, or maybe I am misunderstanding its purpose in this context.

I have a couple of more enhancements I'd like to merge which I'll be in a position to in the next day or so, let me know if I should add them to this pull request or create a new one following on from this one.

Many thanks,
Danny

**Comment by accdc** [comment]
That sounds great! Using the $A methods will help a lot in making it scale across the projects equally.

If you would like to see if these are working as planned within the extended projects, the place to do this is within the TSG archive at
https://github.com/accdc/tsg
Where you can see within the Accessible Component Modules folder, the Calendar module is located. So if you would like to run a test by inserting your modified module there, and check the functionality in the Coding Arena folder if possible within IE11 to check for any runtime errors, plus Firefox and Chrome, and if all works as intended in all of the ARIA Datepicker folder demo.htm examples then it should indeed be working scalably across all of the projects.

I likely won't have time to get to my own testing untill the end of the week, so please feel free to add the additional changes to your code so all of them can be tested for and pulled in at the same time.

About the $A.internal.extend statements, this is actually to address a weird bug that occured within some browsers that were not processing the statement of Object = difObject properly, which was causing some strange issues in the calendar rendering. So, instead, it simply updates the internal variables of each object instead, and that fixed the issue.

Thanks again, and please let me know if there are any other questions I can help with!

Kind regards,
Bryan

**Comment by dannya** [comment]
@accdc I have some potential future changes that I'll be making over the next couple of weeks, so I will bundle any future changes (if any) into a future pull request rather than add any more to this one.

Cheers,
Danny

**Comment by accdc** [comment]
Hi, that sounds great! I'll wait to perform testing on my side until you have these integrated so I don't test anything still in progress. Also, if you could do me a favor and update the ReadMe.txt file within the Coding Arena/ARIA Date Pickers folder within the TSG too so that it includes instructions for using the new functionality that you are adding, that would be great since you can describe how it works much better than I can. :)

**Comment by accdc** [comment]
Hi, as a quick update, I’ve been doing a lot of work to refactor the WhatSock repos and moved all of them under its own umbrella org on GitHub, so this should make it easier to keep track of and merge contrabutions in the future.

 

About the Calendar module update, do you think I should pull these changes in as they are, and then wait to hear back about the other contrabutions? Or do you think all changes should be added so it is all within one pull request when you have these working together as you like? 

 

From a testing perspective, it is easier for me to do the second, because then I can test everything once and not have to worry about doing this again for all repos when it is added to each after the merge.

 

Please let me know, and have a great day,

Bryan

**Comment by dannya** [comment]
Hi @accdc, I think it will be best to wait for my next set of changes which will complement the ones already in this pull request.

I'm working on my other changes now, and hope to have the rest of my changes complete in about 10-14 days.

**Comment by dannya** [comment]
@accdc I've finished my enhancements now (and tested them in the coding arena), ready for review.

I've also made concurrent documentation updates: https://github.com/WhatSock/tsg/pull/14

**Pull request merged**
